const LIST_OF_IMAGE_CATEGORIES = {
  en: ['People', 'Media', 'Camps', 'Other'],
  cn: ['人们', '媒体', '营地', '其他'],
};

const ObJ_OF_STATUS = {
  en: {
    alive: '活',
    deceased: '死者',
    unknown: '未知',
  },
  cn: {
    活: 'alive',
    死者: 'deceased',
    未知: 'unknown',
  },
};

const ObJ_OF_GENDERS = {
  en: {
    male: '男性',
    female: '女性',
    unknown: '未知',
  },
  cn: {
    男性: 'male',
    女性: 'female',
    未知: 'unknown',
  },
};

const ETHNIC_GROUP_CONSTANTS = {
  en: [
    'Han',
    'Zhuang',
    'Hui',
    'Manchu',
    'Uyghur',
    'Miao',
    'Yi',
    'Tujia',
    'Tibetan',
    'Mongol',
    'Dong',
    'Bouyei',
    'Yao',
    'Bai',
    'Joseonjok',
    'Hani',
    'Li',
    'Kazakh',
    'Dai',
    'She',
    'Lisu',
    'Dongxiang',
    'Gelao',
    'Lahu',
    'Wa',
    'Sui',
    'Nakhi',
    'Qiang',
    'Tu',
    'Mulao',
    'Xibe',
    'Kyrgyz',
    'Jingpo',
    'Daur',
    'Salar',
    'Blang',
    'Maonan',
    'Tajik',
    'Pumi',
    'Achang',
    'Nu',
    'Evenki',
    'Vietnamese',
    'Jino',
    'De ang',
    'Bonan',
    'Russian',
    'Yugur',
    'Uzbek',
    'Monba',
    'Oroqen',
    'Derung',
    'Hezhen',
    'Gaoshan',
    'Lhoba',
    'Tatars',
    'Unknown',
    'Naturalized Citizen',
  ],
  en_cn: {
    Han: '汉族',
    Zhuang: '壮族',
    Hui: '回族',
    Manchu: '满族',
    Uyghur: '维吾尔族',
    Miao: '苗族',
    Yi: '彝族',
    Tujia: '土家族',
    Tibetan: '藏族',
    Mongol: '蒙古族',
    Dong: '侗族',
    Bouyei: '布依族',
    Yao: '瑶族',
    Bai: '白族',
    Joseonjok: '朝鲜族',
    Hani: '哈尼族',
    Li: '黎族',
    Kazakh: '哈萨克族',
    Dai: '傣族',
    She: '畲族',
    Lisu: '傈僳族',
    Dongxiang: '东乡族',
    Gelao: '仡佬族',
    Lahu: '拉祜族',
    Wa: '佤族',
    Sui: '水族',
    Nakhi: '纳西族',
    Qiang: '羌族',
    Tu: '土族',
    Mulao: '仫佬族',
    Xibe: '锡伯族',
    Kyrgyz: '柯尔克孜族',
    Jingpo: '景颇族',
    Daur: '达斡尔族',
    Salar: '撒拉族',
    Blang: '布朗族',
    Maonan: '毛南族',
    Tajik: '塔吉克族',
    Pumi: '普米族',
    Achang: '阿昌族',
    Nu: '怒族',
    Evenki: '鄂温克族',
    Vietnamese: '京族',
    Jino: '基诺族',
    'De ang': '德昂族',
    Bonan: '保安族',
    Russian: '俄罗斯族',
    Yugur: '裕固族',
    Uzbek: '乌孜别克族',
    Monba: '门巴族',
    Oroqen: '鄂伦春族',
    Derung: '独龙族',
    Hezhen: '赫哲族',
    Gaoshan: '高山族',
    Lhoba: '珞巴族',
    Tatars: '塔塔尔族',
    Unknown: '未知',
    'Naturalized Citizen': '外国人加入中国籍',
  },
  cn_en: {
    汉族: 'Han',
    壮族: 'Zhuang',
    回族: 'Hui',
    满族: 'Manchu',
    维吾尔族: 'Uyghur',
    苗族: 'Miao',
    彝族: 'Yi',
    土家族: 'Tujia',
    藏族: 'Tibetan',
    蒙古族: 'Mongol',
    侗族: 'Dong',
    布依族: 'Bouyei',
    瑶族: 'Yao',
    白族: 'Bai',
    朝鲜族: 'Joseonjok',
    哈尼族: 'Hani',
    黎族: 'Li',
    哈萨克族: 'Kazakh',
    傣族: 'Dai',
    畲族: 'She',
    傈僳族: 'Lisu',
    东乡族: 'Dongxiang',
    仡佬族: 'Gelao',
    拉祜族: 'Lahu',
    佤族: 'Wa',
    水族: 'Sui',
    纳西族: 'Nakhi',
    羌族: 'Qiang',
    土族: 'Tu',
    仫佬族: 'Mulao',
    锡伯族: 'Xibe',
    柯尔克孜族: 'Kyrgyz',
    景颇族: 'Jingpo',
    达斡尔族: 'Daur',
    撒拉族: 'Salar',
    布朗族: 'Blang',
    毛南族: 'Maonan',
    塔吉克族: 'Tajik',
    普米族: 'Pumi',
    阿昌族: 'Achang',
    怒族: 'Nu',
    鄂温克族: 'Evenki',
    京族: 'Vietnamese',
    基诺族: 'Jino',
    德昂族: 'De ang',
    保安族: 'Bonan',
    俄罗斯族: 'Russian',
    裕固族: 'Yugur',
    乌孜别克族: 'Uzbek',
    门巴族: 'Monba',
    鄂伦春族: 'Oroqen',
    独龙族: 'Derung',
    赫哲族: 'Hezhen',
    高山族: 'Gaoshan',
    珞巴族: 'Lhoba',
    塔塔尔族: 'Tatars',
    未知: 'Unknown',
    外国人加入中国籍: 'Naturalized Citizen',
  },
  cn: [
    '汉族',
    '壮族',
    '回族',
    '满族',
    '维吾尔族',
    '苗族',
    '彝族',
    '土家族',
    '藏族',
    '蒙古族',
    '侗族',
    '布依族',
    '瑶族',
    '白族',
    '朝鲜族',
    '哈尼族',
    '黎族',
    '哈萨克族',
    '傣族',
    '畲族',
    '傈僳族',
    '东乡族',
    '仡佬族',
    '拉祜族',
    '佤族',
    '水族',
    '纳西族',
    '羌族',
    '土族',
    '仫佬族',
    '锡伯族',
    '柯尔克孜族',
    '景颇族',
    '达斡尔族',
    '撒拉族',
    '布朗族',
    '毛南族',
    '塔吉克族',
    '普米族',
    '阿昌族',
    '怒族',
    '鄂温克族',
    '京族',
    '基诺族',
    '德昂族',
    '保安族',
    '俄罗斯族',
    '裕固族',
    '乌孜别克族',
    '门巴族',
    '鄂伦春族',
    '独龙族',
    '赫哲族',
    '高山族',
    '珞巴族',
    '塔塔尔族',
    '未知',
    '外国人加入中国籍',
  ],
};

const LIST_OF_GENDER = {
  en: ['male', 'female', 'unknown'],
  cn: ['男性', '女性', '未知'],
};

const LIST_OF_STATUS = {
  en: ['alive', 'deceased', 'unknown'],
  cn: ['活', '死者', '未知'],
};

export {
  ETHNIC_GROUP_CONSTANTS,
  LIST_OF_GENDER,
  LIST_OF_STATUS,
  LIST_OF_IMAGE_CATEGORIES,
  ObJ_OF_GENDERS,
  ObJ_OF_STATUS,
};
