export const GROUPS = [
  { value: '1', viewValue: 'Han' },
  { value: '2', viewValue: 'Zhuang' },
  { value: '3', viewValue: 'Hui' },
  { value: '4', viewValue: 'Manchu' },
  { value: '5', viewValue: 'Uyghur' },
  { value: '6', viewValue: 'Miao' },
  { value: '7', viewValue: 'Yi' },
  { value: '8', viewValue: 'Tujia' },
  { value: '9', viewValue: 'Tibetan' },
  { value: '10', viewValue: 'Mongol' },
  { value: '11', viewValue: 'Dong' },
  { value: '12', viewValue: 'Bouyei' },
  { value: '13', viewValue: 'Yao' },
  { value: '14', viewValue: 'Bai' },
  { value: '15', viewValue: 'Joseonjok' },
  { value: '16', viewValue: 'Hani' },
  { value: '17', viewValue: 'Li' },
  { value: '18', viewValue: 'Kazakh' },
  { value: '19', viewValue: 'Dai' },
  { value: '20', viewValue: 'She' },
  { value: '21', viewValue: 'Lisu' },
  { value: '22', viewValue: 'Dongxiang' },
  { value: '23', viewValue: 'Gelao' },
  { value: '24', viewValue: 'Lahu' },
  { value: '25', viewValue: 'Wa' },
  { value: '26', viewValue: 'Sui' },
  { value: '27', viewValue: 'Nakhi' },
  { value: '28', viewValue: 'Qiang' },
  { value: '29', viewValue: 'Tu' },
  { value: '30', viewValue: 'Mulao' },
  { value: '31', viewValue: 'Xibe' },
  { value: '32', viewValue: 'Kyrgyz' },
  { value: '33', viewValue: 'Jingpo' },
  { value: '34', viewValue: 'Daur' },
  { value: '35', viewValue: 'Salar' },
  { value: '36', viewValue: 'Blang' },
  { value: '37', viewValue: 'Maonan' },
  { value: '38', viewValue: 'Tajik' },
  { value: '39', viewValue: 'Pumi' },
  { value: '40', viewValue: 'Achang' },
  { value: '41', viewValue: 'Nu' },
  { value: '42', viewValue: 'Evenki' },
  { value: '43', viewValue: 'Vietnamese' },
  { value: '44', viewValue: 'Jino' },
  { value: '45', viewValue: 'De ang' },
  { value: '46', viewValue: 'Bonan' },
  { value: '47', viewValue: 'Russian' },
  { value: '48', viewValue: 'Yugur' },
  { value: '49', viewValue: 'Uzbek' },
  { value: '50', viewValue: 'Monba' },
  { value: '51', viewValue: 'Oroqen' },
  { value: '52', viewValue: 'Derung' },
  { value: '53', viewValue: 'Hezhen' },
  { value: '54', viewValue: 'Gaoshan' },
  { value: '55', viewValue: 'Lhoba' },
  { value: '56', viewValue: 'Tatars' },
  { value: '57', viewValue: 'Unknown' },
  { value: '58', viewValue: 'Naturalized Citizen' },
];

export const CNGROUPS = [
  { value: '1', viewValue: '汉族' },
  { value: '2', viewValue: '壮族' },
  { value: '3', viewValue: '回族' },
  { value: '4', viewValue: '满族' },
  { value: '5', viewValue: '维吾尔族' },
  { value: '6', viewValue: '苗族' },
  { value: '7', viewValue: '彝族' },
  { value: '8', viewValue: '土家族' },
  { value: '9', viewValue: '藏族' },
  { value: '10', viewValue: '蒙古族' },
  { value: '11', viewValue: '侗族' },
  { value: '12', viewValue: '布依族' },
  { value: '13', viewValue: '瑶族' },
  { value: '14', viewValue: '白族' },
  { value: '15', viewValue: '朝鲜族' },
  { value: '16', viewValue: '哈尼族' },
  { value: '17', viewValue: '黎族' },
  { value: '18', viewValue: '哈萨克族' },
  { value: '19', viewValue: '傣族' },
  { value: '20', viewValue: '畲族' },
  { value: '21', viewValue: '傈僳族' },
  { value: '22', viewValue: '东乡族' },
  { value: '23', viewValue: '仡佬族' },
  { value: '24', viewValue: '拉祜族' },
  { value: '25', viewValue: '佤族' },
  { value: '26', viewValue: '水族' },
  { value: '27', viewValue: '纳西族' },
  { value: '28', viewValue: '羌族' },
  { value: '29', viewValue: '土族' },
  { value: '30', viewValue: '仫佬族' },
  { value: '31', viewValue: '锡伯族' },
  { value: '32', viewValue: '柯尔克孜族' },
  { value: '33', viewValue: '景颇族' },
  { value: '34', viewValue: '达斡尔族' },
  { value: '35', viewValue: '撒拉族' },
  { value: '36', viewValue: '布朗族' },
  { value: '37', viewValue: '毛南族' },
  { value: '38', viewValue: '塔吉克族' },
  { value: '39', viewValue: '普米族' },
  { value: '40', viewValue: '阿昌族' },
  { value: '41', viewValue: '怒族' },
  { value: '42', viewValue: '鄂温克族' },
  { value: '43', viewValue: '京族' },
  { value: '44', viewValue: '基诺族' },
  { value: '45', viewValue: '德昂族' },
  { value: '46', viewValue: '保安族' },
  { value: '47', viewValue: '俄罗斯族' },
  { value: '48', viewValue: '裕固族' },
  { value: '49', viewValue: '乌孜别克族' },
  { value: '50', viewValue: '门巴族' },
  { value: '51', viewValue: '鄂伦春族' },
  { value: '52', viewValue: '独龙族' },
  { value: '53', viewValue: '赫哲族' },
  { value: '54', viewValue: '高山族' },
  { value: '55', viewValue: '珞巴族' },
  { value: '56', viewValue: '塔塔尔族' },
  { value: '57', viewValue: '未知' },
  { value: '58', viewValue: '外国人加入中国籍' },
];

export const OCCUPATIONS = [
  { value: '1', viewValue: 'Deputy' },
  { value: '2', viewValue: 'Director' },
  { value: '3', viewValue: 'Professor' },
  { value: '4', viewValue: 'Worker' },
  { value: '5', viewValue: 'Actress' },
  { value: '6', viewValue: 'Agent' },
  { value: '7', viewValue: 'Assistant' },
  { value: '8', viewValue: 'Editor-in-Chief' },
  { value: '9', viewValue: 'Assistant Lieutenant' },
  { value: '10', viewValue: 'Assistant Professor' },
  { value: '11', viewValue: 'Associate Professor' },
  { value: '12', viewValue: 'Cadre' },
  { value: '13', viewValue: 'Chairman' },
  { value: '14', viewValue: 'Chief' },
  { value: '15', viewValue: 'Chief Engineer' },
  { value: '16', viewValue: 'Christian Priest' },
  { value: '17', viewValue: 'Clerk' },
  { value: '18', viewValue: 'Deputy Director' },
  { value: '19', viewValue: 'Deputy Secretary' },
  { value: '20', viewValue: 'Deputy Secretary General' },
  { value: '21', viewValue: 'Doctor' },
  { value: '22', viewValue: 'Editor' },
  { value: '23', viewValue: 'Editorial Editor' },
  { value: '24', viewValue: 'Faculty' },
  { value: '25', viewValue: 'Governor' },
  { value: '26', viewValue: 'Graduate' },
  { value: '27', viewValue: 'Head' },
  { value: '28', viewValue: 'Internship Researcher' },
  { value: '29', viewValue: 'Lieutenant Staff Officer' },
  { value: '30', viewValue: 'Manager' },
  { value: '31', viewValue: 'Member' },
  { value: '32', viewValue: 'Ministry' },
  { value: '33', viewValue: 'Officer' },
  { value: '34', viewValue: 'Painter' },
  { value: '35', viewValue: 'Peasant' },
  { value: '36', viewValue: 'Pilot' },
  { value: '37', viewValue: 'President' },
  { value: '38', viewValue: 'Principal' },
  { value: '39', viewValue: 'Reader' },
  { value: '40', viewValue: 'Research Intern' },
  { value: '41', viewValue: 'Secretary' },
  { value: '42', viewValue: 'Staff' },
  { value: '43', viewValue: 'Student' },
  { value: '44', viewValue: 'Teacher' },
  { value: '45', viewValue: 'Technician' },
  { value: '46', viewValue: 'Trainee' },
  { value: '47', viewValue: 'Vice Chairman' },
  { value: '48', viewValue: 'Vice Dean' },
  { value: '49', viewValue: 'Vice President' },
  { value: '50', viewValue: 'Vice Principal' },
  { value: '51', viewValue: 'Writer' },
  { value: '52', viewValue: 'Unknown' },
];
